---
student_name: lab-user
ocp4_workload_eap_camelq_lab_soap_app_image: quay.io/hayesphilip/rh1-soap-app:latest
ocp4_workload_eap_camelq_lab_postgresql_image: docker.io/library/postgres:14
ocp4_workload_eap_camelq_lab_postgresql_user: postgresUser
ocp4_workload_eap_camelq_lab_postgresql_password: postgresPW
ocp4_workload_eap_camelq_lab_postgresql_db: postgresDB
